"""Config loaders — rules, universe, inception baseline.

`config/rules.json` is hand-maintained from ADR 0003. `config/universe.json` is
generated by scripts/refresh_universe.py. `config/inception.json` is stamped
once, at the first trade, and never rewritten (ADR 0004).
"""

from __future__ import annotations

import json
from pathlib import Path

_CONFIG_DIR = Path(__file__).resolve().parents[2] / "config"

RULES_PATH = _CONFIG_DIR / "rules.json"
UNIVERSE_PATH = _CONFIG_DIR / "universe.json"
INCEPTION_PATH = _CONFIG_DIR / "inception.json"


def load_rules() -> dict:
    return json.loads(RULES_PATH.read_text(encoding="utf-8"))


def load_universe() -> list[str]:
    data = json.loads(UNIVERSE_PATH.read_text(encoding="utf-8"))
    return list(data["tickers"])


def load_inception() -> dict | None:
    """The benchmark baseline, or None if no trade has been placed yet."""
    if not INCEPTION_PATH.is_file():
        return None
    return json.loads(INCEPTION_PATH.read_text(encoding="utf-8"))


def save_inception(d: dict) -> None:
    """Write config/inception.json. Refuses to overwrite an existing baseline —
    a baseline that can be silently rewritten is worse than none (ADR 0004)."""
    if INCEPTION_PATH.exists():
        raise FileExistsError(
            f"{INCEPTION_PATH} already exists; the inception baseline is "
            "immutable and must not be overwritten (ADR 0004)."
        )
    INCEPTION_PATH.write_text(
        json.dumps(d, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
